//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_FlowTask :ModelBase
    {
        public int ID { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> FlowInstanceID { get; set; }
        public Nullable<int> CreatorUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> TaskerUserID { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        [JsonIgnore]
        public virtual UserInfo Authority_User { get; set; }
        [JsonIgnore]
        public virtual UserInfo Authority_User1 { get; set; }
        [JsonIgnore]
        public virtual Flow_FlowInstance Flow_FlowInstance { get; set; }
        [JsonIgnore]
        public virtual Flow_State Flow_State { get; set; }
        [JsonIgnore]
        public virtual Flow_Step Flow_Step { get; set; }
    }
}
