//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using DAL;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GTMDweixinEntities : DbContextBase
    {
        public GTMDweixinEntities()
            : base("name=GTMDweixinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MeunRoleInfo> MeunRoleInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRoleInfo> UserRoleInfoes { get; set; }
        public virtual DbSet<FeedbackInfo> FeedbackInfoes { get; set; }
        public virtual DbSet<NoticeInfo> NoticeInfoes { get; set; }
        public virtual DbSet<ProjectInfo> ProjectInfoes { get; set; }
        public virtual DbSet<SignInfo> SignInfoes { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<StudentProjectInfo> StudentProjectInfoes { get; set; }
        public virtual DbSet<StudentSignInfo> StudentSignInfoes { get; set; }
        public virtual DbSet<MeunInfo> MeunInfoes { get; set; }
        public virtual DbSet<RoleInfo> RoleInfoes { get; set; }
    }
}
