//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeInfo :ModelBase
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Creater { get; set; }
        public string Centent { get; set; }
    }
}
