//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class SignInfo :ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SignInfo()
        {
            this.StudentSignInfos = new HashSet<StudentSignInfo>();
        }
    
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        [JsonIgnore]
        public virtual ProjectInfo ProjectInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<StudentSignInfo> StudentSignInfos { get; set; }
    }
}
