//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSignInfo
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FirstDay_Morning { get; set; }
        public Nullable<System.DateTime> FirstDay_Afternoon { get; set; }
        public Nullable<System.DateTime> FirstDay_Evening { get; set; }
        public Nullable<System.DateTime> SecondDay_Morning { get; set; }
        public Nullable<System.DateTime> SecondDay_Afternoon { get; set; }
        public Nullable<System.DateTime> SecondDay_Evening { get; set; }
        public Nullable<System.DateTime> ThirdDay_Morning { get; set; }
        public Nullable<System.DateTime> ThirdDay_Afternoon { get; set; }
        public Nullable<System.DateTime> ThirdDay_Evening { get; set; }
        public Nullable<System.DateTime> FourthDay_Morning { get; set; }
        public Nullable<System.DateTime> FourthDay_Afternoon { get; set; }
        public Nullable<System.DateTime> FourthDay_Evening { get; set; }
        public Nullable<System.DateTime> FifthDay_Morning { get; set; }
        public Nullable<System.DateTime> FifthDay_Afternoon { get; set; }
        public Nullable<System.DateTime> FifthDay_Evening { get; set; }
        public Nullable<System.DateTime> SixthDay_Morning { get; set; }
        public Nullable<System.DateTime> SixthDay_Afternoon { get; set; }
        public Nullable<System.DateTime> SixthDay_Evening { get; set; }
        public Nullable<System.DateTime> SeventhDay_Morning { get; set; }
        public Nullable<System.DateTime> SeventhDay_Afternoon { get; set; }
        public Nullable<System.DateTime> SeventhDay_Evening { get; set; }
        public int StudentID { get; set; }
        public int SignID { get; set; }
    
        public virtual SignInfo SignInfo { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
