//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSignInfo :ModelBase
    {
        public int ID { get; set; }
        public Nullable<bool> FirstDay_Morning { get; set; }
        public Nullable<bool> FirstDay_Afternoon { get; set; }
        public Nullable<bool> FirstDay_Evening { get; set; }
        public Nullable<bool> SecondDay_Morning { get; set; }
        public Nullable<bool> SecondDay_Afternoon { get; set; }
        public Nullable<bool> SecondDay_Evening { get; set; }
        public Nullable<bool> ThirdDay_Morning { get; set; }
        public Nullable<bool> ThirdDay_Afternoon { get; set; }
        public Nullable<bool> ThirdDay_Evening { get; set; }
        public Nullable<bool> FourthDay_Morning { get; set; }
        public Nullable<bool> FourthDay_Afternoon { get; set; }
        public Nullable<bool> FourthDay_Evening { get; set; }
        public Nullable<bool> FifthDay_Morning { get; set; }
        public Nullable<bool> FifthDay_Afternoon { get; set; }
        public Nullable<bool> FifthDay_Evening { get; set; }
        public Nullable<bool> SixthDay_Morning { get; set; }
        public Nullable<bool> SixthDay_Afternoon { get; set; }
        public Nullable<bool> SixthDay_Evening { get; set; }
        public Nullable<bool> SeventhDay_Morning { get; set; }
        public Nullable<bool> SeventhDay_Afternoon { get; set; }
        public Nullable<bool> SeventhDay_Evening { get; set; }
        public int StudentID { get; set; }
        public int SignID { get; set; }
    
        [JsonIgnore]
        public virtual SignInfo SignInfo { get; set; }
        [JsonIgnore]
        public virtual StudentInfo StudentInfo { get; set; }

        public int Total { get
            {
                return new List<Nullable<bool>>()
                {
                    FirstDay_Morning,FirstDay_Afternoon,FirstDay_Evening,
                    SecondDay_Morning,SecondDay_Afternoon,SecondDay_Evening,
                    ThirdDay_Morning,ThirdDay_Afternoon,ThirdDay_Evening,
                    FourthDay_Morning,FourthDay_Afternoon,FourthDay_Evening,
                    FifthDay_Morning,FifthDay_Afternoon,FifthDay_Evening,
                    SixthDay_Morning,SixthDay_Afternoon,SixthDay_Evening,
                    SeventhDay_Morning,SeventhDay_Afternoon,SeventhDay_Evening
                }.FindAll(item=> Convert.ToBoolean(item)).Count;
            }
        }
        
    }
}
