//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProjectInfo :ModelBase
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
    
        [JsonIgnore]
        public virtual ProjectInfo ProjectInfo { get; set; }
        [JsonIgnore]
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
