//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDweixinManagement.EF
{
    using Newtonsoft.Json;
    using ModelBase;
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo :ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserRoleInfos = new HashSet<UserRoleInfo>();
            this.StudentInfo = new HashSet<StudentInfo>();
            this.Flow_FlowInstance = new HashSet<Flow_FlowInstance>();
            this.Flow_FlowInstance1 = new HashSet<Flow_FlowInstance>();
            this.Flow_FlowTask = new HashSet<Flow_FlowTask>();
            this.Flow_FlowTask1 = new HashSet<Flow_FlowTask>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string MobileTelphoneNumber { get; set; }
        public string IDCardNumber { get; set; }
        public string QQNumber { get; set; }
        public string School { get; set; }
        public string SchoolNumber { get; set; }
        public string Major { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> GreateDate { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<UserRoleInfo> UserRoleInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<StudentInfo> StudentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Flow_FlowInstance> Flow_FlowInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Flow_FlowInstance> Flow_FlowInstance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Flow_FlowTask> Flow_FlowTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Flow_FlowTask> Flow_FlowTask1 { get; set; }
    }
}
